spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: student
          uri: http://localhost:8082
          predicates:
            - Path=/students/**
          filters:
            - JwtAuthenticationFilter

        - id: school-service
          uri: http://localhost:8080
          predicates:
            - Path=/schools/**
          filters:
            - JwtAuthenticationFilter

        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
